// GENERATED by scripts/gen_shadow_assets.py — DO NOT EDIT.
// Regenerate after any gui/style.py shadow/accent/budget token change:
//   python scripts/gen_shadow_assets.py
// (tests/test_qml_kit_surface.py's manifest drift-guard fails loudly if the
// baked assets no longer match the live tokens.)
//
// 9-patch geometry contract: every shadow asset represents [fill rect
// expanded by shadowPad] — a BorderImage anchors.fill's the fill item with
// anchors.margins: -shadowPad[level] and border: shadowBorder[level]. The
// halo asset uses haloPad/haloBorder the same way. washPeakAlpha /
// sweepPeakAlpha are the living-ground tint-budget split baked into the
// wash sprites (band law, kit_spec_v1.md §5.3).
pragma Singleton
import QtQuick

QtObject {
    readonly property real washPeakAlpha: 0.03
    readonly property real sweepPeakAlpha: 0.01
    readonly property var shadowPad: ({
        "contact": 5, "card": 34,
        "pane": 54, "float": 114
    })
    readonly property var shadowBorder: ({
        "contact": 19, "card": 56,
        "pane": 80, "float": 136
    })
    readonly property int haloPad: 14
    readonly property int haloBorder: 28
}
