"""SettingsWindow's devices.yaml persistence must preserve comments.

Regression coverage for the comment-eating yaml.safe_load -> yaml.dump round
trip that used to live in ``_on_quick_settings_changed`` (TECH_DEBT.md RISK
2026-07-10, second occurrence 2026-07-11: the waveform_generator
level_low_V/level_high_V unipolar-trigger comment block was deleted twice).
Both ``_on_quick_settings_changed`` (in-memory editor text) and ``_save``
(the actual file write) are exercised end to end here, following the
existing gui test idiom (see test_settings_window_panel_kit_rollout.py):
``QT_QPA_PLATFORM=offscreen``, a shared ``QApplication.instance()`` helper,
no pytest-qt.
"""
from __future__ import annotations

import os

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

import shutil
from pathlib import Path

import pytest
import yaml
from PySide6.QtWidgets import QApplication

from gui.settings_window import SettingsWindow

_REAL_CONFIG = Path(__file__).resolve().parents[1] / "configs" / "devices.yaml"


@pytest.fixture(autouse=True)
def _stub_visa_scan(monkeypatch):
    """Same rationale as test_settings_window_panel_kit_rollout.py: avoid a
    real VISA bus enumeration off-thread during the test."""
    monkeypatch.setattr("devices.waveform_generator.list_visa_resources", lambda: [])


@pytest.fixture(autouse=True)
def _stub_save_dialog(monkeypatch):
    """``_save()`` pops a blocking QMessageBox.information on success --
    stub it so a headless ``_save()`` call doesn't hang the test."""
    monkeypatch.setattr("gui.settings_window.QMessageBox.information", lambda *a, **k: None)


def _app() -> QApplication:
    return QApplication.instance() or QApplication([])


def _tmp_config(tmp_path: Path) -> Path:
    """A copy of the real devices.yaml (with its manual-cited comment
    blocks) that tests are free to mutate."""
    dst = tmp_path / "devices.yaml"
    shutil.copy(_REAL_CONFIG, dst)
    assert "# level_low_V: 0.0" in dst.read_text(encoding="utf-8"), (
        "fixture precondition: configs/devices.yaml must still carry the "
        "wavegen comment block for this regression test to mean anything"
    )
    return dst


def test_quick_settings_change_preserves_wavegen_comment_block(tmp_path):
    _app()
    cfg_path = _tmp_config(tmp_path)
    win = SettingsWindow(config_path=cfg_path)
    try:
        # Touch an unrelated oscilloscope widget -> fires `changed` ->
        # `_on_quick_settings_changed`, which used to regenerate the whole
        # YAML document via yaml.dump and drop every comment.
        win._scope_section._n_avg.setValue(win._scope_section._n_avg.value() + 1)
        text = win._editor.toPlainText()
        assert "# level_low_V: 0.0" in text
        assert "# level_high_V: 2.5" in text
    finally:
        win.close()


def test_quick_settings_change_does_not_prepend_generated_header(tmp_path):
    """The old lossy path prepended a fresh "# Generated by Quick Settings"
    banner on every change (a symptom of regenerating the whole document);
    the comment-preserving merge no longer does that."""
    _app()
    doc = _REAL_CONFIG.read_text(encoding="utf-8")
    doc = "\n".join(
        line for line in doc.splitlines()
        if "Generated by Quick Settings" not in line
    ) + "\n"
    cfg_path = tmp_path / "devices.yaml"
    cfg_path.write_text(doc, encoding="utf-8")
    win = SettingsWindow(config_path=cfg_path)
    try:
        win._scope_section._n_avg.setValue(win._scope_section._n_avg.value() + 1)
        text = win._editor.toPlainText()
        assert "# Generated by Quick Settings" not in text
    finally:
        win.close()


def test_save_writes_comment_block_to_disk(tmp_path):
    _app()
    cfg_path = _tmp_config(tmp_path)
    win = SettingsWindow(config_path=cfg_path)
    try:
        win._scope_section._n_avg.setValue(win._scope_section._n_avg.value() + 1)
        win._save()
        on_disk = cfg_path.read_text(encoding="utf-8")
        assert "# level_low_V: 0.0" in on_disk
        assert "# level_high_V: 2.5" in on_disk
        cfg = yaml.safe_load(on_disk)
        assert cfg["oscilloscope"]["n_averages"] >= 1
    finally:
        win.close()


def test_bias_supply_simulation_key_round_trips_and_keeps_comment_block(tmp_path):
    """Paul's bias_supply.simulation toggle (2026-07-11, landed concurrently
    with this fix) is an always-written key from ``_BiasSection.to_dict()``
    -- exactly the kind of "new key through the new persistence path" case
    that needs its own regression pin, not just incidental coverage via the
    other tests here."""
    _app()
    cfg_path = _tmp_config(tmp_path)
    before = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    assert before["bias_supply"]["simulation"] is True  # fixture precondition

    win = SettingsWindow(config_path=cfg_path)
    try:
        idx = win._bias_section._sim.findText("false")
        assert idx >= 0
        win._bias_section._sim.setCurrentIndex(idx)
        win._save()
        on_disk = cfg_path.read_text(encoding="utf-8")
        assert "# level_low_V: 0.0" in on_disk
        assert "# level_high_V: 2.5" in on_disk
        cfg = yaml.safe_load(on_disk)
        assert cfg["bias_supply"]["simulation"] is False
        assert cfg["bias_supply"]["backend"] == "iseg"  # untouched sibling key
        assert cfg["bias_supply"]["visa_address"] == "ASRL6::INSTR"
    finally:
        win.close()


def test_motor_backend_switch_preserves_comment_block_and_updates_keys(tmp_path):
    """motor_stage previously did a wholesale dict *replace* on every Quick
    Settings change; the comment-preserving merge only rewrites/appends the
    keys the widget actually emits (see settings_window.py docstring note on
    stale backend-specific keys)."""
    _app()
    cfg_path = _tmp_config(tmp_path)
    win = SettingsWindow(config_path=cfg_path)
    try:
        idx = win._motor_section._backend.findText("pi")
        assert idx >= 0
        win._motor_section._backend.setCurrentIndex(idx)
        text = win._editor.toPlainText()
        assert "# level_low_V: 0.0" in text
        cfg = yaml.safe_load(text)
        assert cfg["motor_stage"]["backend"] == "pi"
        assert cfg["motor_stage"]["velocity"] == win._motor_section._pi_velocity.value()
    finally:
        win.close()
